### ISSUE TITLE
docker image(GPU) failed to built

### ISSUE THREAD

**Issue by aprentis** [gosha20777/rescuer-la#7]
Hi! 
i've tried to build GPU-version of docker image on my ubuntu 16.04(nvidia 418.67, Cuda 10.1 and got this error in the end. 

sudo docker build --file Dockerfile.gpu -t rescuer_la .
Sending build context to Docker daemon  14.56MB
Step 1/24 : FROM tensorflow/tensorflow:1.12.0-gpu-py3
 ---> 413b9533f92a
Step 2/24 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 8a52f51116f2
Step 3/24 : RUN apt-get update -qq  && apt-get install --no-install-recommends -y     build-essential     g++     git     wget     apt-transport-https     curl     cython     libopenblas-base     python3-numpy     python3-scipy     python3-h5py     python3-yaml     python3-pydot  && apt-get clean  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> a545cb38439e
Step 4/24 : RUN pip3 --no-cache-dir install -U numpy==1.13.3
 ---> Using cache
 ---> 98d345ea0a28
Step 5/24 : ARG KERAS_VERSION=2.2.4
 ---> Using cache
 ---> 7b09457df232
Step 6/24 : ENV KERAS_BACKEND=tensorflow
 ---> Using cache
 ---> 85a448c8d80b
Step 7/24 : RUN pip3 --no-cache-dir install --no-dependencies git+https://github.com/fchollet/keras.git@${KERAS_VERSION}
 ---> Using cache
 ---> 1c91dbe3620b
Step 8/24 : RUN python3 -c "import tensorflow; print(tensorflow.__version__)"  && dpkg-query -l > /dpkg-query-l.txt  && pip3 freeze > /pip3-freeze.txt
 ---> Running in 08e7f4469a36
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
The command '/bin/sh -c python3 -c "import tensorflow; print(tensorflow.__version__)"  && dpkg-query -l > /dpkg-query-l.txt  && pip3 freeze > /pip3-freeze.txt' returned a non-zero code: 1

**Comment by gosha20777** [comment]
Make sure that your nvidia GPU is turned on and nvidia-docker and nvidia-driver is installed.

**Comment by gosha20777** [comment]
this issue fixed at 50dd900

**Comment by gosha20777** [comment]
@aprentis please see [0.2.1](https://github.com/gosha20777/rescuer-la/releases/tag/0.2.1) release.
