### ISSUE TITLE
docker image(CPU) failed to start.

### ISSUE THREAD

**Issue by aprentis** [gosha20777/rescuer-la#8]
Hi, i`ve successfully built CPU image, but it failed to start with this error. 

sudo docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --workdir=$(pwd) --volume="/home/$USER:/home/$USER" --volume="/etc/group:/etc/group:ro" --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" --volume="/etc/sudoers.d:/etc/sudoers.d:ro" rescuer_la
No protocol specified
No protocol specified

Unhandled Exception: System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at RescuerLaApp.Program.Main(String[] args) in /app/install/RescuerLaApp/Program.cs:line 14

**Comment by gosha20777** [comment]
This is because your display socket is not redirected correctly.
Try to use `sudo xhost +` command

**Comment by aprentis** [comment]
Yeah, this worked for me, thx!
